server {
    listen 80;
    server_name DOMAIN;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name DOMAIN;

    ssl_certificate /etc/xray/ssl/fullchain.pem;
    ssl_certificate_key /etc/xray/ssl/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        root /var/www/html;
        index index.html;
    }

    location ^~ /vless {
        rewrite ^/vless.*$ /vless break;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location ^~ /vmess {
        rewrite ^/vmess.*$ /vmess break;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location ^~ /trojan-ws {
        rewrite ^/trojan-ws.*$ /trojan-ws break;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10003;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /vless-grpc {
        grpc_pass grpc://127.0.0.1:10005;
    }

    location /vmess-grpc {
        grpc_pass grpc://127.0.0.1:10006;
    }

    location /trojan-grpc {
        grpc_pass grpc://127.0.0.1:10007;
    }

    location ^~ /ss-ws {
        rewrite ^/ss-ws.*$ /ss-ws break;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10008;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /ss-grpc {
        grpc_pass grpc://127.0.0.1:10009;
    }
}
