#!/bin/bash

USERNAME=$1
PASSWORD=$2
EXPIRED_AT=$3
IPLIMIT="5"

IP=$(curl -s ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
DOMAIN=$(cat /etc/xray/domain)

if [ ! -e /etc/xray/sshx ]; then
mkdir -p /etc/xray/sshx
fi
if [ ! -e /etc/xray/sshx/akun ]; then
mkdir -p /etc/xray/sshx/akun
fi
if [ -z ${IPLIMIT} ]; then
IPLIMIT="0"
fi
echo "${IPLIMIT}" >/etc/xray/sshx/${USERNAME}IP

useradd -e "${EXPIRED_AT}" -s /bin/false -M "${USERNAME}" &> /dev/null
echo -e "${PASSWORD}\n${PASSWORD}\n" | passwd "${USERNAME}" &> /dev/null
echo -e "### ${USERNAME} ${EXPIRED_AT} ${PASSWORD}" >> /etc/xray/ssh

cat > /var/www/html/ssh-$USERNAME.txt <<-END
=========================
   SmileVpn Tunneling 
=========================

Format SSH OVPN Account
=========================
Username         : $USERNAME
Password         : $PASSWORD
=========================
ISP              : $ISP
CITY             : $CITY
IP               : $IP
Host             : $DOMAIN
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH UDP     : 1-65535
Port SSH WS      : 80, 8080, 8081-9999
Port SSH SSL WS  : 443
Port SSL/TLS     : 400-900
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 1194
Port OVPN UDP    : 2200
BadVPN UDP       : 7100, 7300, 7300
=================================
Payload WSS: GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $DOMAIN[crlf]Upgrade: websocket[crlf][crlf] 
=================================
Payload Enchanced: PATCH / HTTP/1.1[crlf]Host: [host][crlf]Host: bug.com[crlf]Upgrade: websocket[crlf]HTTP/ 3600[crlf]Sec-WebSocket-Extensions: superspeed[crlf]
=================================
SSH TLS/SNI : $DOMAIN:443@$USERNAME:$PASSWORD
SSH Non TLS : $DOMAIN:80@$USERNAME:$PASSWORD
=================================
OVPN Download : https://$DOMAIN:81/
=================================
Berakhir Pada    : $EXPIRED_AT
=================================

END

cat /etc/xray/sshx/akun/log-create-${USERNAME}.log


cat > /etc/xray/sshx/akun/log-create-${USERNAME}.log <<EOF
🔐 SSH ACCOUNT

Username   : ${USERNAME}
Password   : ${PASSWORD}
Expired    : ${EXPIRED_AT}
Limit IP   : ${IPLIMIT} IP

🌐 SERVER
Domain     : ${DOMAIN}
IP         : ${IP}
City       : ${CITY}

🔌 PORT
SSH        : 443, 80, 22
Dropbear   : 443, 109
WS         : 80, 8080, 8081-9999
SSL WS     : 443
UDP        : 1-65535

🔗 LINK
OVPN       : https://${DOMAIN}:81/
Save       : https://${DOMAIN}:81/ssh-${USERNAME}.txt
HTTP UDP   : ${DOMAIN}:1-65535@${USERNAME}:${PASSWORD}

📡 PAYLOAD
GET / HTTP/1.1[crlf]
Host: ${DOMAIN}[crlf]
Upgrade: websocket[crlf][crlf]
EOF

