#!/bin/bash

USERNAME=$1
EXPIRED_AT=$2


sed -i "/^#tr ${USERNAME} ${EXPIRED_AT}/,/^,{/d" /etc/xray/config.json
sed -i "/^#trg ${USERNAME} ${EXPIRED_AT}/,/^,{/d" /etc/xray/config.json

rm -f /etc/trojan/${USERNAME}IP >/dev/null 2>&1
rm -f /etc/trojan/$USERNAME
rm -f /var/www/html/trojan-$USERNAME.txt
rm -f /etc/trojan/akun/log-create-${USERNAME}.log
rm -f /etc/limit/trojan/${USERNAME}
systemctl restart xray > /dev/null 2>&1
