#!/bin/bash

USERNAME=$1
EXPIRED_AT=$2
IPLIMIT="5"
QUOTA="0"

IP=$(curl -s ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
DOMAIN=$(cat /etc/xray/domain)

if [ ! -e /etc/trojan ]; then
mkdir -p /etc/trojan
fi
if [ ! -e /etc/trojan/akun ]; then
mkdir -p /etc/trojan/akun
fi
if [ ${IPLIMIT} = '0' ]; then
IPLIMIT="9999"
fi
if [ ${QUOTA} = '0' ]; then
QUOTA="999"
fi
c=$(echo "${QUOTA}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
echo "${d}" >/etc/trojan/${USERNAME}
fi
echo "${IPLIMIT}" >/etc/trojan/${USERNAME}IP
#ISP=$(cat /etc/xray/isp)
#CITY=$(cat /etc/xray/city)
# shellcheck disable=SC2002
TLS="443"
# shellcheck disable=SC2002
NTLS="80"
UUID=$(cat /proc/sys/kernel/random/uuid)
TROJAN_LINK_TLS="trojan://${UUID}@isi_bug_disini:${TLS}?path=%2Ftrojan-ws%2Fmultipath&security=tls&host=${DOMAIN}&type=ws&sni=${DOMAIN}#${USERNAME}"
TROJAN_LINK_GRPC="trojan://${UUID}@${DOMAIN}:${TLS}?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=bug.com#${USERNAME}"
TROJAN_LINK_NTLS="trojan://${UUID}@isi_bug_disini:${NTLS}?path=%2Ftrojan-ws%2Fmultipath&security=none&host=${DOMAIN}&type=ws#${USERNAME}"

# shellcheck disable=SC2027
# shellcheck disable=SC2086
# shellcheck disable=SC1004
sed -i '/#trojanws$/a\#tr '"$USERNAME $EXPIRED_AT"'\
,{"password": "'""${UUID}""'","email": "'""${USERNAME}""'"}' /etc/xray/config.json
# shellcheck disable=SC2027
# shellcheck disable=SC2086
# shellcheck disable=SC1004
sed -i '/#trojangrpc$/a\#trg '"$USERNAME $EXPIRED_AT"'\
,{"password": "'""${UUID}""'","email": "'""${USERNAME}""'"}' /etc/xray/config.json


systemctl restart xray > /dev/null 2>&1

cat >/var/www/html/trojan-$USERNAME.txt <<-END
=========================
   SmileVPN Tunneling 
=========================

# Format Trojan GO/WS

- name: $USERNAME
  server: ${DOMAIN}
  port: 443
  type: trojan
  password: ${UUID}
  network: ws
  sni: ${DOMAIN}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws/multipath
    headers:
  Host: ${DOMAIN}

# Format Trojan gRPC

- name: $USERNAME
  type: trojan
  server: ${DOMAIN}
  port: 443
  password: ${UUID}
  udp: true
  sni: ${DOMAIN}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc

END



cat > /etc/trojan/akun/log-create-${USERNAME}.log <<EOF
🔐 TROJAN ACCOUNT

Username   : ${USERNAME}
Key        : ${UUID}
Expired    : ${EXPIRED_AT}
Limit IP   : ${IPLIMIT} IP
Quota      : ${QUOTA} GB

🌐 SERVER
Domain     : ${DOMAIN}
IP         : ${IP}
City       : ${CITY}

🔌 PORT
TLS        : ${TLS}
Non TLS    : ${NTLS}
gRPC       : ${TLS}
Path       : /trojan-ws/multipath
Service    : trojan-grpc

🔗 LINK
OpenClash  : https://${DOMAIN}:81/trojan-${USERNAME}.txt

TLS
${TROJAN_LINK_TLS}

Non TLS
${TROJAN_LINK_NTLS}

gRPC
${TROJAN_LINK_GRPC}
EOF

cat /etc/trojan/akun/log-create-${USERNAME}.log
