#!/bin/bash
USERNAME=$1
EXPIRED_AT=$2
IPLIMIT="${3:-5}"
QUOTA="9999"

[ -z "$USERNAME" ] && exit 1
[ -z "$EXPIRED_AT" ] && exit 1

[ "$EXPIRED_AT" = "trial" ] && EXPIRED_AT=$(date -d "+1 hour" "+%Y-%m-%d %H:%M")

UUID=$(cat /proc/sys/kernel/random/uuid)
DOMAIN=$(cat /etc/xray/domain)
IP=$(cat /etc/xray/ip 2>/dev/null || curl -s ipv4.icanhazip.com)
PUBLIC_KEY=$(cat /etc/xray/reality_public)
SHORT_ID=$(cat /etc/xray/reality_short)

mkdir -p /etc/vlessreality /var/www/html

echo "$IPLIMIT" >/etc/vlessreality/${USERNAME}IP

VR_LINK="vless://${UUID}@${DOMAIN}:8443?security=reality&encryption=none&type=tcp&flow=xtls-rprx-vision&sni=www.cloudflare.com&fp=chrome&pbk=${PUBLIC_KEY}&sid=${SHORT_ID}#${USERNAME}"

sed -i '/#vlessreality$/a\#vr '"${USERNAME} ${EXPIRED_AT}"'\
,{"id":"'"${UUID}"'","flow":"xtls-rprx-vision","email":"'"${USERNAME}"'"}' /etc/xray/config.json

systemctl restart xray >/dev/null 2>&1

cat > /var/www/html/vless-reality-${USERNAME}.txt <<END
proxies:
-  name: ${USERNAME}
  server: ${DOMAIN}
  port: 8443
  type: vless
  uuid: ${UUID}
  flow: xtls-rprx-vision
  network: tcp
  tls: true
  servername: www.cloudflare.com
  client-fingerprint: chrome
  reality-opts:
    public-key: ${PUBLIC_KEY}
    short-id: ${SHORT_ID}
  udp: true

# LINK
${VR_LINK}
END

cat /var/www/html/vless-reality-${USERNAME}.txt
