#!/bin/bash

USERNAME=$1
EXPIRED_AT=$2
IPLIMIT="5"
QUOTA="0"

IP=$(curl -s ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
DOMAIN=$(cat /etc/xray/domain)


if [ ! -e /etc/vless ]; then
mkdir -p /etc/vless
fi
if [ ! -e /etc/vless/akun ]; then
mkdir -p /etc/vless/akun
fi
if [ ${IPLIMIT} = '0' ]; then
IPLIMIT="9999"
fi
if [ ${QUOTA} = '0' ]; then
QUOTA="9999"
fi
c=$(echo "${QUOTA}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
echo "${d}" >/etc/vless/${USERNAME}
fi
echo "${IPLIMIT}" >/etc/vless/${USERNAME}IP
# shellcheck disable=SC2002
TLS="443"
# shellcheck disable=SC2002
NTLS="80"
UUID=$(cat /proc/sys/kernel/random/uuid)
VLESS_LINK_TLS="vless://${UUID}@${DOMAIN}:${TLS}?path=/vless/multipath&security=tls&encryption=none&type=ws#${USERNAME}"
VLESS_LINK_NTLS="vless://${UUID}@${DOMAIN}:${NTLS}?path=/vless/multipath&encryption=none&type=ws#${USERNAME}"
VLESS_LINK_GRPC="vless://${UUID}@${DOMAIN}:${TLS}?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=bug.com#${USERNAME}"

# shellcheck disable=SC2027
# shellcheck disable=SC2086
# shellcheck disable=SC1004
sed -i '/#vless$/a\#vl '"${USERNAME} ${EXPIRED_AT}"'\
,{"id": "'""${UUID}""'","email": "'""${USERNAME}""'"}' /etc/xray/config.json
# shellcheck disable=SC2027
# shellcheck disable=SC2086
# shellcheck disable=SC1004
sed -i '/#vlessgrpc$/a\#vlg '"${USERNAME} ${EXPIRED_AT}"'\
,{"id": "'""${UUID}""'","email": "'""${USERNAME}""'"}' /etc/xray/config.json

systemctl restart xray > /dev/null 2>&1

cat >/var/www/html/vless-$USERNAME.txt <<-END

=========================
  SmileVPN TUNNELING 
=========================
# Format Vless WS TLS

- name: $USERNAME
  server: ${DOMAIN}
  port: 443
  type: vless
  uuid: ${UUID}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${DOMAIN}
  network: ws
  ws-opts:
    path: /vless/multipath
    headers:
  Host: ${DOMAIN}

# Format Vless WS Non TLS

- name: $USERNAME
  server: ${DOMAIN}
  port: 80
  type: vless
  uuid: ${UUID}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${DOMAIN}
  network: ws
  ws-opts:
    path: /vless/multipath
    headers:
      Host: ${DOMAIN}
  udp: true

# Format Vless gRPC (SNI)

- name: $USERNAME
  server: ${DOMAIN}
  port: 443
  type: vless
  uuid: ${UUID}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${DOMAIN}
  network: grpc
  grpc-opts:
  grpc-mode: gun
    grpc-service-name: vless-grpc

=========================
Link Akun Vless 
=========================
Link TLS      : 
${VLESS_LINK_TLS}
=========================
Link none TLS : 
${VLESS_LINK_NTLS}
=========================
Link GRPC     : 
${VMESS_LINK_GRPC}
=========================

END

cat > /etc/vless/akun/log-create-${USERNAME}.log <<EOF
🔐 VLESS ACCOUNT

Username   : ${USERNAME}
UUID       : ${UUID}
Expired    : ${EXPIRED_AT}
Limit IP   : ${IPLIMIT} IP

🌐 SERVER
Domain     : ${DOMAIN}
IP         : ${IP}
City       : ${CITY}

🔌 PORT
TLS        : 443
Non TLS    : 80
gRPC       : 443
Path       : /vless/multipath
Service    : vless-grpc

🔗 LINK
OpenClash  : https://${DOMAIN}:81/vless-${USERNAME}.txt

TLS
${VLESS_LINK_TLS}

Non TLS
${VLESS_LINK_NTLS}

gRPC
${VLESS_LINK_GRPC}
EOF

