#!/bin/bash

USERNAME=$1
EXPIRED_AT=$2

if [ -z "$USERNAME" ] || [ -z "$EXPIRED_AT" ]; then
    echo "Usage: vless-reality-renew-account USERNAME YYYY-MM-DD"
    exit 1
fi

EXP=$(grep -wE "^#vr ${USERNAME}" /etc/xray/config.json | cut -d ' ' -f 3 | head -n1)
sed -i "s/#vr ${USERNAME} ${EXP}/#vr ${USERNAME} ${EXPIRED_AT}/g" /etc/xray/config.json

systemctl restart xray >/dev/null 2>&1
