#!/bin/bash

USERNAME=$1

if [ -z "$USERNAME" ]; then
    echo "Usage: vless-reality-delete-account USERNAME"
    exit 1
fi

sed -i "/^#vr ${USERNAME} /,/^,{/d" /etc/xray/config.json

rm -f /etc/vlessreality/${USERNAME}IP
rm -f /etc/vlessreality/${USERNAME}
rm -f /etc/vlessreality/akun/log-create-${USERNAME}.log
rm -f /var/www/html/vless-reality-${USERNAME}.txt

systemctl restart xray >/dev/null 2>&1
